---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: directory
    path: docs
    label: Developer Docs
    create: documents/developer/
    match: "*.md"
    templates:
      - page
  - type: directory
    path: docs
    label: Docs
    create: documents
    match: "*.md"
    templates:
      - docs
  - type: directory
    path: blog
    label: Blog
    create: documents
    match: "*.md"
upload_dir: static/img
public_path: "/img"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm i
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
